package com.example.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.bean.Customers;
import com.example.dao.CustomersDAO;

@Service
public class CustomerService {

	@Autowired
	CustomersDAO customerDAO;
	
	public List<Customers> getAllCustomers(){
		List<Customers> customerList = customerDAO.listCustomers();
		return customerList;
	}
	
	public Customers getCustomerByID(Long id) {
		Customers customer = customerDAO.getCustomerByID(id);
		return customer;
	}
	
	public Customers addCustomer(Customers customer) throws Exception{
		if (!validateCustomerRequest(customer)) 
		{
			throw new Exception("INVALID REQUEST");
		}
		else 
		{
			customerDAO.addCustomer(customer);
			return customer;
		}
	}

//only have to check for name + email within request since ID is generated by Database once added
	private boolean validateCustomerRequest(Customers customer) {
		if(customer.getName() != null && !customer.getName().isEmpty() 
				&& customer.getEmail() !=null && !customer.getEmail().isEmpty()) 
		{
			return true;
		}
		else return false;
	}
}
